# Matrix data type.
Matrix is vector with a dimension attribute. The dimesion attribute itself is an integer vector that has the Rows and Columns information. Matrix always takes all elements of the same type. If forced with various data types as elements coercion converts all the elements to a same data type.  

In [21]:
# Creating a matrix 
A = matrix(1:15, nrow = 3, ncol = 5)
print(A)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    4    7   10   13
[2,]    2    5    8   11   14
[3,]    3    6    9   12   15


# Matrices coercion

In [13]:
# Can a matrix be inserted with a heterogenious elements? 
# First create matrix
mat_A = matrix(0, nrow =5, ncol = 3)
print(mat_A)
# test to know the class type of an element in the matrix
print(class(mat_A[2,3])) # it is numeric type.
# Now try feeding a character here and see 
mat_A[2,3] <- 'sree'
print(mat_A)
# Great coercion works here and changes all the elements to 
#characters


     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0
[1] "numeric"
     [,1] [,2] [,3]  
[1,] "0"  "0"  "0"   
[2,] "0"  "0"  "sree"
[3,] "0"  "0"  "0"   
[4,] "0"  "0"  "0"   
[5,] "0"  "0"  "0"   
